[window]
dynamic_padding = true
title = "Terminal"
dynamic_title = false
decorations = "None"
opacity = 0.75

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout = 0

[font]
#normal = { family = "unifont" }
size = 13

[colors.primary]
foreground = "#fdfdfd"
background = "#000000"

[colors.normal]
black	= "#222222"
red		= "#f01818"
green	= "#24d830"
yellow	= "#f0d824"
blue	= "#7890f0"
magenta	= "#f078d8"
cyan	= "#54e4e4"
white	= "#a5a5a5"

[colors.bright]
black	= "#888888"
red		= "#ef8383"
green	= "#7ed684"
yellow	= "#efe28b"
blue	= "#b3bfef"
magenta	= "#efb3e3"
cyan	= "#9ce2e2"
white	= "#ffffff"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "PageUp", action = "ScrollHalfPageup" },
{ key = "PageDown", action = "ScrollHalfPagedown" },
{ key = "Home", action = "ScrollToTop" },
{ key = "End", action = "ScrollToBottom" },
]
