# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto --human-readable'
alias grep='grep --color=auto'
alias vim='nvim'
alias tree='tree -C'

PS1="\w\$ "

eval "$(fzf --bash)"
